# Generated by Django 3.1 on 2020-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(max_length=3, verbose_name='Genre du patient')),
                ('code', models.CharField(max_length=30)),
                ('date_prelevement', models.DateField(verbose_name='Date du prélèvement')),
                ('date_traitement', models.DateField()),
                ('copies_ARN', models.CharField(max_length=20, verbose_name='nombre de copies ARN')),
                ('log_copies_ARN', models.CharField(max_length=20, verbose_name='Log ARN')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
