# Generated by Django 3.1 on 2020-09-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilansangin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='date_prelevement',
            field=models.DateField(null=True, verbose_name='Date du prélèvement'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='date_traitement',
            field=models.DateField(null=True),
        ),
    ]
